<?php
/**
 +----------------------------------------------------------------------+
 | CiviCRM version 1.0                                                  |
 +----------------------------------------------------------------------+
 | Copyright (c) 2005 Donald A. Lobo                                    |
 +----------------------------------------------------------------------+
 | This file is a part of CiviCRM.                                      |
 |                                                                      |
 | CiviCRM is free software; you can redistribute it and/or modify it   |
 | under the terms of the Affero General Public License Version 1,      |
 | March 2002.                                                          |
 |                                                                      |
 | CiviCRM is distributed in the hope that it will be useful, but       |
 | WITHOUT ANY WARRANTY; without even the implied warranty of           |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                 |
 | See the Affero General Public License for more details at            |
 | http://www.affero.org/oagpl.html                                     |
 |                                                                      |
 | A copy of the Affero General Public License has been been            |
 | distributed along with this program (affero_gpl.txt)                 |
 +----------------------------------------------------------------------+
*/

/**
 * Drupal module file.
 *
 * @package CRM
 * @author Donald A. Lobo <lobo@yahoo.com>
 * @copyright Donald A. Lobo 01/15/2005
 * $Id$
 *
 */


include_once 'config.inc.php';

require_once 'PEAR.php';

require_once 'CRM/Core/Action.php';
require_once 'CRM/Core/Form.php';
require_once 'CRM/Core/Block.php';
require_once 'CRM/Core/Selector/Controller.php';
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Core/PseudoConstant.php';
require_once 'CRM/Core/Invoke.php';

require_once 'CRM/Core/BAO/UFMatch.php';

require_once 'CRM/Utils/Menu.php';
require_once 'CRM/Utils/Wrapper.php';

require_once 'CRM/Contact/Page/View.php';

require_once 'CRM/Core/Error.php';


/**
 * Provides a link to the CSS stylesheet associated with this module.
 *
 * @return a &lt;style&gt; tag that indicates what file browsers should import
 */
function civicrm_html_head()
{
    $config = CRM_Core_Config::singleton();
    return '<style type="text/css">@import url(' . $config->resourceBase . 'css/civicrm.css);</style>';
}

/**
 * @file
 * This is an example outlining how a module can be used to display a
 * custom page at a given URL.
 */

/**
 * Implementation of hook_help().
 *
 * Throughout Drupal, hook_help() is used to display help text at the top of
 * pages. Some other parts of Drupal pages get explanatory text from these hooks
 * as well. We use it here to provide a description of the module on the
 * module administration page. This example also illustrates how to add help
 * text to the pages your module defines.
 */
function civicrm_help($section)
{
    switch ($section) {
    case 'admin/modules#description':
        // This description is shown in the listing at admin/modules.
        return ts('CiviCRM module v0.1');
    }
}

/**
 * Implementation of hook_perm().
 *
 * Since the access to our new custom pages will be granted based on
 * special permissions, we need to define what those permissions are here.
 * This ensures that they are available to enable on the user role
 * administration pages.
 */
function civicrm_perm()
{
    // static permissions
    $cPerm = array('add contacts', 'view all contacts', 'edit all contacts', 'edit groups', 'administer CiviCRM', 'access CiviCRM' );

    // dynamic permissions - access by group (title)
    $groups =& CRM_Core_PseudoConstant::allGroup();
    foreach ( $groups as $title ) {
        $cPerm[] = 'view ' . $title;
        $cPerm[] = 'edit ' . $title;
    }

    $savedSearches =& CRM_Core_PseudoConstant::allSavedSearch( );
    foreach ( $savedSearches as $title ) {
        $cPerm[] = 'view ' . $title;
        $cPerm[] = 'edit ' . $title;
    }

    return $cPerm;
}

/**
 * Implementation of hook_block().
 *
 * This hook both declares to Drupal what blocks are provided by the module, and
 * generates the contents of the blocks themselves.
 */

function civicrm_block($op='list', $delta='0')
{
    if ( ( arg(0) != 'civicrm' && arg(0) != 'admin' ) || ( ! user_access( 'access CiviCRM' ) ) ) {
        return;
    }

    // The $op parameter determines what piece of information is being requested.
    global $user;
    if ($user->uid) {
        $menu_arr = civicrm_menu(true);
        if ($op == 'list') {
            return CRM_Core_Block::getInfo();
        } else {
            return CRM_Core_Block::getContent ($delta);
        }
    }
}

/**
 * Implementation of hook_menu().
 *
 * You must implement hook_menu() to emit items to place in the main menu.
 * This is a required step for modules wishing to display their own pages,
 * because the process of creating the links also tells Drupal what
 * callback function to use for a given URL. The menu items returned
 * here provide this information to the menu system.
 *
 * With the below menu definitions, URLs will be interpreted as follows:
 *
 * If the user accesses http://example.com/?q=foo, then the menu system
 * will first look for a menu item with that path. In this case it will
 * find a match, and execute civicrm_foo().
 *
 */
function civicrm_menu($may_cache)
{
    // The $may_cache parameter is used to divide menu items into two parts. Those
    // returned when $may_cache is true must be consistently applicable for the
    // current user at all times; the others may change or be defined at only
    // certain paths. Most modules will have excusively cacheable menu items.
    
    if ($may_cache) {
        return CRM_Utils_Menu::items( );
    }
    return CRM_Utils_Menu::items( );

}

function civicrm_hack_path($path, $qs)
{
    $items = explode('/', $path);
    $len   = count($items) ;
    if (arg($len - 1) != $items[$len - 1]) {
        return CRM_Utils_System::url($path, $qs, false);
    } else {
        return $path;
    }
}

/**
 * implementation of hook_init
 *
 */
function civicrm_init()
{
    if ( arg(0) != 'civicrm' && arg(0) != 'admin' && arg(0) != 'user' ) {
        return;
    }

    if ( arg(0) == 'civicrm' ) {
        menu_rebuild();
    }

    $config =& CRM_Core_Config::singleton();
    CRM_Core_DAO::init($config->dsn, $config->daoDebug);
    
    $factoryClass = 'CRM_Contact_DAO_Factory';
    
    CRM_Core_DAO::setFactory(new $factoryClass());

    // Add module-specific stylesheet to page header
    drupal_set_html_head(civicrm_html_head());

    // set error handling
    PEAR::setErrorHandling(PEAR_ERROR_CALLBACK, array('CRM_Core_Error', 'handle'));
}

/**
 * exit hook, make sure we sync between drupal and crm here
 */
function civicrm_exit($destination = null)
{
    // if the user edited the user record stuff might have changed so do a resync
    if (arg(0) == 'user' && arg(2) == 'edit' && ! empty($_POST)) {
        global $user;
        CRM_Core_BAO_UFMatch::synchronize( $user, true, 'Drupal' );
    }
        
}

function civicrm_invoke()
{
    // synchronize the drupal uid with the contacts db
    global $user;
    CRM_Core_BAO_UFMatch::synchronize( $user, false, 'Drupal' );

    $args = explode( '/', $_GET['q'] );
	return CRM_Core_Invoke::invoke( $args );
}

/**
 * User hook for civicrm module
 *
 * @param string $type     Type of operation being performed
 * @param array  $edit     The array of form values submitted by the user.
 * @param object $user     The user object on which the operation is being performed.
 * @param object $category The active category of user information being edited.
 *
 * @return mixed           depends on the operation being performed
 */
function civicrm_user( $type, &$edit, &$user, $category = NULL ) {
    /**
    CRM_Core_Error::debug( 't', $type );
    CRM_Core_Error::debug( 't', $edit );
    CRM_Core_Error::debug( 'u', $user );
    **/

    switch ( $type ) {

    case 'load':
        return civicrm_load_data($user);

    case 'login':
        return CRM_Core_BAO_UFMatch::synchronize( $user, false, 'Drupal' );

    case 'register':
    case 'insert':
        return civicrm_register_data($edit, $user, $category);

    case 'view':
        return civicrm_view_data($user);

    case 'update':
    case 'form':
        return civicrm_form_data($edit, $user, $category, false);

    case 'validate':
        return civicrm_validate_data($edit, $category);

    case 'categories':
        return civicrm_categories();
    }

}

function civicrm_categories( ) {
    $ufGroups =& CRM_Core_PseudoConstant::ufGroup( );
    
    $data = array( );
    foreach ( $ufGroups as $id => $title ) {
        $data[] = array( 'name'  => $title,
                         'title' => $title,
                         'weight' => 5 );
    }
    return $data;
}

function civicrm_load_data(&$user) {
}

function civicrm_register_data($edit, &$user, $category) {
    $output = array( );
    if ( $user->uid ) {
        CRM_Core_BAO_UFMatch::synchronize( $user, true, 'Drupal' );
    }

    $html = CRM_Core_BAO_UFGroup::getEditHTML( '', null, true );
    $output[] = array( 'title' => 'CiviCRM Information', 'data' => $html, weight => 0 );
    return $output;
}

function civicrm_form_data($edit, &$user, $category) {
    // get all the data for this specific category
    $html = CRM_Core_BAO_UFGroup::getEditHTML( $category, null, false );
    
    $output = array( );
    $output[] = array( 'title' => $category, 'data' => $html, weight => 0 );
    return $output;
}

function civicrm_save_data(&$edit, &$user, $category) {
}

function civicrm_view_data($user ) {
    $ufGroups =& CRM_Core_PseudoConstant::ufGroup( );

    $data = array( );
    foreach ( $ufGroups as $id => $title ) {
        $data[$title] = CRM_Core_BAO_UFGroup::getEditHTML( $title, CRM_Core_Action::VIEW, false );
    }
    return $data;
}

function civicrm_validate_data($edit, $title) {
    $register = ( $title == 'account' ) ? true : false;
    if ( ! CRM_Core_BAO_UFGroup::isValid( $title, $register ) ) {
        form_set_error( 'error', 'Please correct the errors in the form fields below' );
    }
    return;
}

?>
