# admin page

require 'test_admin_gender'
require 'test_admin_IMProvider'
require 'test_admin_mobile_provider'
require 'test_admin_activity'
require 'test_admin_prefix'
require 'test_admin_suffix'
require 'test_admin_tag'
require 'test_admin_location'
require 'test_admin_profile'
require 'test_admin_membership_type'
require 'test_admin_option_group'
require 'test_manage_group'
require 'test_admin_contribution_types'
require 'test_admin_payment_instrument'
require 'test_admin_accept_credit_card'
require 'test_admin_accept_credit_card'
require 'test_admin_duplicate_matching'
require 'test_admin_import_export_mapping'
require 'test_admin_custom_data'
