<?php

/**
 * Define potential seperators that can be used in various
 * scripts (specifically this is kinda important in various
 * import routines
 */
define( 'WGM_SEPERATOR_COMMA'    ,   ","    );
define( 'WGM_SEPERATOR_SEMICOLON',   ";"    );
define( 'WGM_SEPERATOR_TAB'      ,   "\t"   );
define( 'WGM_SEPERATOR_SPACE'    ,   " "    );
define( 'WGM_SEPERATOR_LF'       ,   "\n"   );
define( 'WGM_SEPERATOR_CRLF'     ,   "\r\n" );
define( 'WGM_SEPERATOR_LFCR'     ,   "\n\r" );
define( 'WGM_SEPERATOR_CR'       ,   "\r"   );

?>
