/*!40101 SET NAMES utf8 */;

/*******************************************************
*
* civicrm_county (!! TBD)
*
* Look at importing county tables (re: Advokit)
*
*******************************************************/



INSERT INTO civicrm_country (id, name,iso_code) VALUES("1001", "Afghanistan", "AF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1002", "Albania", "AL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1003", "Algeria", "DZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1004", "American Samoa", "AS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1005", "Andorra", "AD");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1006", "Angola", "AO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1007", "Anguilla", "AI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1008", "Antarctica", "AQ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1009", "Antigua and Barbuda", "AG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1010", "Argentina", "AR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1011", "Armenia", "AM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1012", "Aruba", "AW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1013", "Australia", "AU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1014", "Austria", "AT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1015", "Azerbaijan", "AZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1016", "Bahrain", "BH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1017", "Bangladesh", "BD");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1018", "Barbados", "BB");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1019", "Belarus", "BY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1020", "Belgium", "BE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1021", "Belize", "BZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1022", "Benin", "BJ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1023", "Bermuda", "BM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1024", "Bhutan", "BT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1025", "Bolivia", "BO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1026", "Bosnia and Herzegovina", "BA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1027", "Botswana", "BW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1028", "Bouvet Island", "BV");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1029", "Brazil", "BR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1030", "British Indian Ocean Territory", "IO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1031", "Virgin Islands, British", "VG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1032", "Brunei Darussalam", "BN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1033", "Bulgaria", "BG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1034", "Burkina Faso", "BF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1035", "Myanmar", "MM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1036", "Burundi", "BI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1037", "Cambodia", "KH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1038", "Cameroon", "CM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1039", "Canada", "CA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1040", "Cape Verde", "CV");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1041", "Cayman Islands", "KY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1042", "Central African Republic", "CF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1043", "Chad", "TD");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1044", "Chile", "CL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1045", "China", "CN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1046", "Christmas Island", "CX");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1047", "Cocos (Keeling) Islands", "CC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1048", "Colombia", "CO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1049", "Comoros", "KM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1050", "Congo, The Democratic Republic of the", "CD");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1051", "Congo", "CG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1052", "Cook Islands", "CK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1053", "Costa Rica", "CR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1054", "Côte d\'Ivoire", "CI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1055", "Croatia", "HR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1056", "Cuba", "CU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1057", "Cyprus", "CY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1058", "Czech Republic", "CZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1059", "Denmark", "DK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1060", "Djibouti", "DJ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1061", "Dominica", "DM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1062", "Dominican Republic", "DO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1063", "Timor-Leste", "TL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1064", "Ecuador", "EC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1065", "Egypt", "EG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1066", "El Salvador", "SV");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1067", "Equatorial Guinea", "GQ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1068", "Eritrea", "ER");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1069", "Estonia", "EE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1070", "Ethiopia", "ET");
-- INSERT INTO civicrm_country (id, name,iso_code) VALUES("1071", "European Union", "EU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1072", "Falkland Islands (Malvinas)", "FK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1073", "Faroe Islands", "FO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1074", "Fiji", "FJ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1075", "Finland", "FI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1076", "France", "FR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1077", "French Guiana", "GF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1078", "French Polynesia", "PF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1079", "French Southern Territories", "TF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1080", "Gabon", "GA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1081", "Georgia", "GE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1082", "Germany", "DE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1083", "Ghana", "GH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1084", "Gibraltar", "GI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1085", "Greece", "GR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1086", "Greenland", "GL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1087", "Grenada", "GD");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1088", "Guadeloupe", "GP");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1089", "Guam", "GU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1090", "Guatemala", "GT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1091", "Guinea", "GN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1092", "Guinea-Bissau", "GW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1093", "Guyana", "GY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1094", "Haiti", "HT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1095", "Heard Island and McDonald Islands", "HM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1096", "Holy See (Vatican City State)", "VA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1097", "Honduras", "HN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1098", "Hong Kong", "HK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1099", "Hungary", "HU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1100", "Iceland", "IS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1101", "India", "IN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1102", "Indonesia", "ID");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1103", "Iran, Islamic Republic of", "IR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1104", "Iraq", "IQ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1105", "Ireland", "IE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1106", "Israel", "IL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1107", "Italy", "IT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1108", "Jamaica", "JM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1109", "Japan", "JP");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1110", "Jordan", "JO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1111", "Kazakhstan", "KZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1112", "Kenya", "KE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1113", "Kiribati", "KI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1114", "Korea, Democratic People\'s Republic of", "KP");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1115", "Korea, Republic of", "KR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1116", "Kuwait", "KW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1117", "Kyrgyzstan", "KG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1118", "Lao People\'s Democratic Republic", "LA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1119", "Latvia", "LV");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1120", "Lebanon", "LB");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1121", "Lesotho", "LS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1122", "Liberia", "LR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1123", "Libyan Arab Jamahiriya", "LY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1124", "Liechtenstein", "LI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1125", "Lithuania", "LT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1126", "Luxembourg", "LU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1127", "Macao", "MO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1128", "Macedonia, Republic of", "MK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1129", "Madagascar", "MG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1130", "Malawi", "MW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1131", "Malaysia", "MY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1132", "Maldives", "MV");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1133", "Mali", "ML");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1134", "Malta", "MT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1135", "Marshall Islands", "MH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1136", "Martinique", "MQ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1137", "Mauritania", "MR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1138", "Mauritius", "MU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1139", "Mayotte", "YT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1140", "Mexico", "MX");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1141", "Micronesia, Federated States of", "FM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1142", "Moldova, Republic of", "MD");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1143", "Monaco", "MC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1144", "Mongolia", "MN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1145", "Montserrat", "MS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1146", "Morocco", "MA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1147", "Mozambique", "MZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1148", "Namibia", "NA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1149", "Nauru", "NR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1150", "Nepal", "NP");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1151", "Netherlands Antilles", "AN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1152", "Netherlands", "NL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1153", "New Caledonia", "NC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1154", "New Zealand", "NZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1155", "Nicaragua", "NI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1156", "Niger", "NE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1157", "Nigeria", "NG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1158", "Niue", "NU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1159", "Norfolk Island", "NF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1160", "Northern Mariana Islands", "MP");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1161", "Norway", "NO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1162", "Oman", "OM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1163", "Pakistan", "PK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1164", "Palau", "PW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1165", "Palestinian Territory, Occupied", "PS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1166", "Panama", "PA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1167", "Papua New Guinea", "PG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1168", "Paraguay", "PY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1169", "Peru", "PE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1170", "Philippines", "PH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1171", "Pitcairn", "PN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1172", "Poland", "PL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1173", "Portugal", "PT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1174", "Puerto Rico", "PR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1175", "Qatar", "QA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1176", "Romania", "RO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1177", "Russian Federation", "RU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1178", "Rwanda", "RW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1179", "Reunion", "RE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1180", "Saint Helena", "SH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1181", "Saint Kitts and Nevis", "KN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1182", "Saint Lucia", "LC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1183", "Saint Pierre and Miquelon", "PM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1184", "Saint Vincent and the Grenadines", "VC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1185", "Samoa", "WS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1186", "San Marino", "SM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1187", "Saudi Arabia", "SA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1188", "Senegal", "SN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1189", "Seychelles", "SC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1190", "Sierra Leone", "SL");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1191", "Singapore", "SG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1192", "Slovakia", "SK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1193", "Slovenia", "SI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1194", "Solomon Islands", "SB");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1195", "Somalia", "SO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1196", "South Africa", "ZA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1197", "South Georgia and the South Sandwich Islands", "GS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1198", "Spain", "ES");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1199", "Sri Lanka", "LK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1200", "Sudan", "SD");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1201", "Suriname", "SR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1202", "Svalbard and Jan Mayen", "SJ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1203", "Swaziland", "SZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1204", "Sweden", "SE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1205", "Switzerland", "CH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1206", "Syrian Arab Republic", "SY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1207", "Sao Tome and Principe", "ST");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1208", "Taiwan", "TW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1209", "Tajikistan", "TJ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1210", "Tanzania, United Republic of", "TZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1211", "Thailand", "TH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1212", "Bahamas", "BS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1213", "Gambia", "GM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1214", "Togo", "TG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1215", "Tokelau", "TK");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1216", "Tonga", "TO");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1217", "Trinidad and Tobago", "TT");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1218", "Tunisia", "TN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1219", "Turkey", "TR");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1220", "Turkmenistan", "TM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1221", "Turks and Caicos Islands", "TC");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1222", "Tuvalu", "TV");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1223", "Uganda", "UG");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1224", "Ukraine", "UA");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1225", "United Arab Emirates", "AE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1226", "United Kingdom", "GB");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1227", "United States Minor Outlying Islands", "UM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1228", "United States", "US");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1229", "Uruguay", "UY");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1230", "Uzbekistan", "UZ");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1231", "Vanuatu", "VU");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1232", "Venezuela", "VE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1233", "Viet Nam", "VN");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1234", "Virgin Islands, U.S.", "VI");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1235", "Wallis and Futuna", "WF");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1236", "Western Sahara", "EH");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1237", "Yemen", "YE");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1238", "Serbia and Montenegro", "CS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1239", "Zambia", "ZM");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1240", "Zimbabwe", "ZW");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1241", "Åland Islands", "AX");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1242", "Serbia", "RS");
INSERT INTO civicrm_country (id, name,iso_code) VALUES("1243", "Montenegro", "ME");
