/*!40101 SET NAMES utf8 */;

/*******************************************************
*
* civicrm_county (!! TBD)
*
* Look at importing county tables (re: Advokit)
*
*******************************************************/


INSERT INTO civicrm_worldregion (id, name) VALUES("1", "Europe and Central Asia");
INSERT INTO civicrm_worldregion (id, name) VALUES("2", "South America, North America and Carribean");
INSERT INTO civicrm_worldregion (id, name) VALUES("3", "Middle East and North Africa");
INSERT INTO civicrm_worldregion (id, name) VALUES("4", "Asia-Pacific");
INSERT INTO civicrm_worldregion (id, name) VALUES("5", "Central and South Africa");


INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1001", "Afghanistan", "AF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1002", "Albania", "AL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1003", "Algeria", "DZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1004", "American Samoa", "AS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1005", "Andorra", "AD", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1006", "Angola", "AO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1007", "Anguilla", "AI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1008", "Antarctica", "AQ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1009", "Antigua and Barbuda", "AG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1010", "Argentina", "AR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1011", "Armenia", "AM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1012", "Aruba", "AW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1013", "Australia", "AU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1014", "Austria", "AT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1015", "Azerbaijan", "AZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1016", "Bahrain", "BH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1017", "Bangladesh", "BD", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1018", "Barbados", "BB", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1019", "Belarus", "BY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1020", "Belgium", "BE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1021", "Belize", "BZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1022", "Benin", "BJ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1023", "Bermuda", "BM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1024", "Bhutan", "BT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1025", "Bolivia", "BO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1026", "Bosnia and Herzegovina", "BA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1027", "Botswana", "BW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1028", "Bouvet Island", "BV", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1029", "Brazil", "BR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1030", "British Indian Ocean Territory", "IO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1031", "Virgin Islands, British", "VG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1032", "Brunei Darussalam", "BN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1033", "Bulgaria", "BG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1034", "Burkina Faso", "BF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1035", "Myanmar", "MM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1036", "Burundi", "BI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1037", "Cambodia", "KH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1038", "Cameroon", "CM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1039", "Canada", "CA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1040", "Cape Verde", "CV", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1041", "Cayman Islands", "KY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1042", "Central African Republic", "CF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1043", "Chad", "TD", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1044", "Chile", "CL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1045", "China", "CN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1046", "Christmas Island", "CX", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1047", "Cocos (Keeling) Islands", "CC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1048", "Colombia", "CO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1049", "Comoros", "KM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1050", "Congo, The Democratic Republic of the", "CD", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1051", "Congo", "CG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1052", "Cook Islands", "CK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1053", "Costa Rica", "CR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1054", "Côte d\'Ivoire", "CI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1055", "Croatia", "HR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1056", "Cuba", "CU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1057", "Cyprus", "CY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1058", "Czech Republic", "CZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1059", "Denmark", "DK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1060", "Djibouti", "DJ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1061", "Dominica", "DM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1062", "Dominican Republic", "DO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1063", "Timor-Leste", "TL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1064", "Ecuador", "EC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1065", "Egypt", "EG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1066", "El Salvador", "SV", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1067", "Equatorial Guinea", "GQ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1068", "Eritrea", "ER", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1069", "Estonia", "EE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1070", "Ethiopia", "ET", "1");
-- INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1071", "European Union", "EU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1072", "Falkland Islands (Malvinas)", "FK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1073", "Faroe Islands", "FO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1074", "Fiji", "FJ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1075", "Finland", "FI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1076", "France", "FR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1077", "French Guiana", "GF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1078", "French Polynesia", "PF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1079", "French Southern Territories", "TF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1080", "Gabon", "GA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1081", "Georgia", "GE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1082", "Germany", "DE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1083", "Ghana", "GH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1084", "Gibraltar", "GI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1085", "Greece", "GR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1086", "Greenland", "GL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1087", "Grenada", "GD", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1088", "Guadeloupe", "GP", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1089", "Guam", "GU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1090", "Guatemala", "GT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1091", "Guinea", "GN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1092", "Guinea-Bissau", "GW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1093", "Guyana", "GY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1094", "Haiti", "HT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1095", "Heard Island and McDonald Islands", "HM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1096", "Holy See (Vatican City State)", "VA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1097", "Honduras", "HN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1098", "Hong Kong", "HK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1099", "Hungary", "HU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1100", "Iceland", "IS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1101", "India", "IN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1102", "Indonesia", "ID", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1103", "Iran, Islamic Republic of", "IR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1104", "Iraq", "IQ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1105", "Ireland", "IE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1106", "Israel", "IL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1107", "Italy", "IT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1108", "Jamaica", "JM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1109", "Japan", "JP", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1110", "Jordan", "JO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1111", "Kazakhstan", "KZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1112", "Kenya", "KE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1113", "Kiribati", "KI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1114", "Korea, Democratic People\'s Republic of", "KP", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1115", "Korea, Republic of", "KR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1116", "Kuwait", "KW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1117", "Kyrgyzstan", "KG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1118", "Lao People\'s Democratic Republic", "LA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1119", "Latvia", "LV", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1120", "Lebanon", "LB", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1121", "Lesotho", "LS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1122", "Liberia", "LR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1123", "Libyan Arab Jamahiriya", "LY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1124", "Liechtenstein", "LI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1125", "Lithuania", "LT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1126", "Luxembourg", "LU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1127", "Macao", "MO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1128", "Macedonia, Republic of", "MK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1129", "Madagascar", "MG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1130", "Malawi", "MW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1131", "Malaysia", "MY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1132", "Maldives", "MV", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1133", "Mali", "ML", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1134", "Malta", "MT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1135", "Marshall Islands", "MH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1136", "Martinique", "MQ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1137", "Mauritania", "MR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1138", "Mauritius", "MU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1139", "Mayotte", "YT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1140", "Mexico", "MX", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1141", "Micronesia, Federated States of", "FM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1142", "Moldova, Republic of", "MD", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1143", "Monaco", "MC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1144", "Mongolia", "MN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1145", "Montserrat", "MS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1146", "Morocco", "MA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1147", "Mozambique", "MZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1148", "Namibia", "NA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1149", "Nauru", "NR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1150", "Nepal", "NP", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1151", "Netherlands Antilles", "AN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1152", "Netherlands", "NL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1153", "New Caledonia", "NC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1154", "New Zealand", "NZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1155", "Nicaragua", "NI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1156", "Niger", "NE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1157", "Nigeria", "NG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1158", "Niue", "NU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1159", "Norfolk Island", "NF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1160", "Northern Mariana Islands", "MP", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1161", "Norway", "NO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1162", "Oman", "OM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1163", "Pakistan", "PK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1164", "Palau", "PW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1165", "Palestinian Territory, Occupied", "PS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1166", "Panama", "PA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1167", "Papua New Guinea", "PG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1168", "Paraguay", "PY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1169", "Peru", "PE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1170", "Philippines", "PH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1171", "Pitcairn", "PN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1172", "Poland", "PL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1173", "Portugal", "PT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1174", "Puerto Rico", "PR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1175", "Qatar", "QA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1176", "Romania", "RO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1177", "Russian Federation", "RU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1178", "Rwanda", "RW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1179", "Reunion", "RE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1180", "Saint Helena", "SH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1181", "Saint Kitts and Nevis", "KN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1182", "Saint Lucia", "LC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1183", "Saint Pierre and Miquelon", "PM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1184", "Saint Vincent and the Grenadines", "VC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1185", "Samoa", "WS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1186", "San Marino", "SM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1187", "Saudi Arabia", "SA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1188", "Senegal", "SN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1189", "Seychelles", "SC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1190", "Sierra Leone", "SL", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1191", "Singapore", "SG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1192", "Slovakia", "SK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1193", "Slovenia", "SI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1194", "Solomon Islands", "SB", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1195", "Somalia", "SO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1196", "South Africa", "ZA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1197", "South Georgia and the South Sandwich Islands", "GS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1198", "Spain", "ES", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1199", "Sri Lanka", "LK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1200", "Sudan", "SD", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1201", "Suriname", "SR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1202", "Svalbard and Jan Mayen", "SJ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1203", "Swaziland", "SZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1204", "Sweden", "SE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1205", "Switzerland", "CH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1206", "Syrian Arab Republic", "SY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1207", "Sao Tome and Principe", "ST", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1208", "Taiwan", "TW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1209", "Tajikistan", "TJ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1210", "Tanzania, United Republic of", "TZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1211", "Thailand", "TH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1212", "Bahamas", "BS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1213", "Gambia", "GM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1214", "Togo", "TG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1215", "Tokelau", "TK", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1216", "Tonga", "TO", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1217", "Trinidad and Tobago", "TT", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1218", "Tunisia", "TN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1219", "Turkey", "TR", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1220", "Turkmenistan", "TM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1221", "Turks and Caicos Islands", "TC", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1222", "Tuvalu", "TV", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1223", "Uganda", "UG", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1224", "Ukraine", "UA", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1225", "United Arab Emirates", "AE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1226", "United Kingdom", "GB", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1227", "United States Minor Outlying Islands", "UM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1228", "United States", "US", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1229", "Uruguay", "UY", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1230", "Uzbekistan", "UZ", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1231", "Vanuatu", "VU", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1232", "Venezuela", "VE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1233", "Viet Nam", "VN", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1234", "Virgin Islands, U.S.", "VI", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1235", "Wallis and Futuna", "WF", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1236", "Western Sahara", "EH", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1237", "Yemen", "YE", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1238", "Serbia and Montenegro", "CS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1239", "Zambia", "ZM", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1240", "Zimbabwe", "ZW", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1241", "Åland Islands", "AX", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1242", "Serbia", "RS", "1");
INSERT INTO civicrm_country (id, name,iso_code,region_id) VALUES("1243", "Montenegro", "ME", "1");
