.\"                                      Hey, EMACS: -*- nroff -*-
.\" $Id: amavisd-new.8 799 2006-01-30 23:54:32Z hmh $
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AMAVISD-NEW 8 "2003-01-01"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
amavisd-new \- Interface between MTA and virus scanner/content filters
.SH SYNOPSIS
.B amavisd-new
[
.B -u
.I userid
]
[
.B -g
.I groupid
]
[
.B -c
.I config-file
]...
[
.B start
|
.B stop
|
.B reload
|
.B debug
|
.B debug-sa
|
.B foreground
]
.br
.SH DESCRIPTION
.B amavisd
is a high-performance interface between message transfer
agent (MTA) and virus scanners and/or spam scanners.
.PP
This is the amavisd-new incarnation of amavisd.  It is a performance-enhanced
and feature-enriched version of the original amavisd program.
.PP
Amavisd-new works as a SMTP proxy.  Email is fed to it through SMTP, processed,
and fed back to the MTA through a new SMTP connection.  There is no buffering
to disk by amavis, it will report that the transfer was sucessfull only after
the forwarding MTA has accepted the message.
.PP
It is possible to use the sendmail milter interface instead of the SMTP
proxy method, as well.
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
.TP
.B \-c configfile
Use the specified configuration file instead of using run-parts(8) to find
config files in /usr/share/amavis/conf.d and /etc/amavis/conf.d (this is a
Debian extension to Amavisd-new).  More than one \-c option can be specified
and the files will be read in the order given.
.TP
.B \-u userid
Try to switch to that user id.
.TP
.B \-g groupid
Try to switch to that group id.
.TP
.B start
Starts amavisd-new
.TP
.B stop
Stops a running amavisd-new
.TP
.B reload
Reloads configuration from config file (may in fact just restart amavisd-new)
.TP
.B debug
Runs amavisd-new in debug mode
.TP
.B debug-sa
Runs amavisd-new in spamassassin debug mode
.TP
.B foreground
Does not fork to background
.SH FILES
.BR /etc/amavis/amavisd.conf,
.BR /var/lib/amavis,
.BR /var/run/amavis/amavisd.pid
.SH SEE ALSO
.BR /usr/share/doc/amavisd-new/*
.br
.SH AUTHOR
This manual page was written by Henrique de Moraes Holschuh <hmh@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
